services:
  postgres:
    image: postgres:17
    container_name: postgres_qr
    env_file: 
      - ./backend/.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  pgadmin:
    container_name: pgadmin_qr
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
      
  backend:
    build: ./backend
    environment:
    - DB_HOST=postgres
    ports:
    - "9000:9000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/requirements.txt:/app/requirements.txt
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:80"
  #   depends_on:
  #     - backend

    
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_IAD
  #   ports:
  #     - "9090:80"
  #   volumes:
  #     - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./frontend/dist:/usr/share/nginx/html:ro
  #   depends_on:
  #     - backend
  #     - frontend

volumes:
  pgdata:
  pgadmin-data: